
spring.datasource.url=jdbc:postgresql://localhost:5433/mini_mundo_db

spring.datasource.username=minimundo_user

spring.datasource.password=minimundo_pwd

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true